### ISSUE TITLE
Drupal 8 Contrib Porting

### ISSUE THREAD

**Issue by bighappyface** [tableau-mkt/datalayer#7]
Hey Team,

May we get started on migrating `datalayer` to D8?

https://www.drupal.org/project/contrib_tracker

**Comment by doublejosh** [comment]
Have at it! Thanks.

**Comment by iairrozen** [comment]
Hello everyone.
I'm looking to implement this on D8 Lightning distro by acquia and I was wondering if the current version is compatible or if I have to modify the code somehow.

Thanks.

**Comment by doublejosh** [comment]
This Drupal user was potentially getting sponsored to port to D8.
https://www.drupal.org/u/rhuffstedtler

**Comment by bighappyface** [comment]
@doublejosh the community is ready to go with the 8.x-1.x version of this module.

https://www.drupal.org/node/2832411

@blakestein has even taken the liberty of getting things started:

https://github.com/blakestein/drupal-datalayer-d8

I understand it is tricky to juggle a project with the repo being in github and d.o, but many of us are ready to help.

May I help by becoming a maintainer on the d.o side? I would take collaborator status here as well to help manage the branches (an 8.x-1.x branch would be great in github and d.o). I maintain several other project and am happy to help keep things moving for this great module.

**Comment by bighappyface** [comment]
@doublejosh ^^

**Comment by doublejosh** [comment]
Thank you. Will happily add you as a maintainer. Sorry for the delay.

**Comment by bighappyface** [comment]
Thanks @doublejosh!

**Comment by bighappyface** [comment]
https://www.drupal.org/project/datalayer/releases/8.x-1.x-dev
