### ISSUE TITLE
GTM Data Layer Best Practices

### ISSUE THREAD

**Issue by evan-rosa-bah** [tableau-mkt/datalayer#8]
After reviewing the injected data layer code I noticed that it's not following best practice guidelines. To meet this requirement, you should use:

window.dataLayer = window.dataLayer || [];
window.dataLayer.push({...});

RATHER THAN: 
var dataLayer = [{...}];

https://www.analyticsmania.com/post/datalayer-push/#gref
https://www.simoahava.com/analytics/100-google-tag-manager-learnings/#20-never-overwrite-always-push

**Comment by jkopel** [comment]
Thanks @evan-rosa-bah please feel free to submit a PR for us to review or submit a patch directly to the Drupal queue! (https://www.drupal.org/project/datalayer)
